# -*- coding: utf-8 -*-
"""python_jogo_adivinhacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/engqroz-io/imersao_ia_alura_google/blob/main/labs/python_jogo_adivinhacao.ipynb
"""

import requests

url = 'https://raw.githubusercontent.com/guilhermeonrails/api-imersao-ia/main/words.json'
resposta = requests.get(url)
data = resposta.json()
len(data)

data[0]

import random

valor_secreto = random.choice(data)
palavra_secreta = valor_secreto['palavra']
dica = valor_secreto['dica']
print(f'A palavra secreta tem {len(palavra_secreta)} letras')
print(f'A dica é -> {dica}')
chute = input('O que você acha que é: ')
if chute == palavra_secreta:
  print('Acertou')
else:
  print(f'Errou a palavra secreta é: {palavra_secreta}')